#!/usr/bin/env
args = commandArgs(trailingOnly=TRUE)
library(ggplot2)
library(reshape)
# setwd('/Users/Dimitra/Google\ Drive/DiffSeq_Paper/PipelineForV3_edits/DataFolder/CoveragePET17/')
# dat=read.table('1kb-4_S23_Coverage.txt',sep="\t",header=T)
# Total coverage frequencies for figure S2B
dat=read.table(args[1],sep="\t",header=T)
pdf(args[2],width=10, height=6)
par(mar=c(4.5,4.5,1,1))
FWD=sum(dat$TotFWD)
RVS=sum(dat$TotRVS)
plot(dat$Position,dat$TotFWD/FWD, type='h',xlab ="Reference position", ylab="Coverage frequency", col = "blue", cex.lab=2, cex.axis=2, ylim=c(-0.01, 0.015))
lines(dat$Position,dat$TotRVS*(-1.0)/RVS, type='h', col = "red")
plot(dat$Position,dat$TotFWD/FWD, type='h',xlab ="Reference position", ylab="Coverage frequency", col = "blue", cex.lab=2, cex.axis=2, xlim=c(460, 500), ylim=c(-0.01, 0.015))
lines(dat$Position,dat$TotRVS*(-1.0)/RVS, type='h', col = "red")
dev.off()

# Diff-seq coverage frequencies per nucleotide for figures 2, S3 and S2C
pdf(args[3],width=10, height=6)
par(mar=c(4,4,1,1))
datfwd.m = cbind(dat$Position, dat$dsAFWD, dat$dsCFWD, dat$dsGFWD, dat$dsTFWD)
datrvs.m = cbind(dat$Position, dat$dsARVS, dat$dsCRVS, dat$dsGRVS, dat$dsTRVS)
datfwd = data.frame(datfwd.m)
datrvs = data.frame(datrvs.m)
# names(datfwd)
# names(datrvs)
datf = melt(datfwd, id=c("X1"))
datr = melt(datrvs, id=c("X1"))
FWD=sum(datf$value)
RVS=sum(datr$value)
ggplot() +geom_bar(data=datf,aes(x=X1,y=value/FWD,fill=variable),stat="identity",position="stack")+geom_bar(data=datr,aes(x=X1,y=value*(-1)/RVS,fill=variable),stat="identity",position="stack")+ scale_y_continuous(limits = c(-0.1, 0.25))+labs(x="Reference position",y = "Diff-seq Coverage Frequencies")+theme_bw(base_size = 20)+ theme(panel.background = element_rect(fill ="transparent", colour = "black"),panel.grid.minor = element_blank(),panel.grid.major = element_blank())+theme(axis.text=element_text(size=20),axis.title=element_text(size=20),legend.text=element_text(size=16),legend.title=element_text(size=18))
ggplot() +geom_bar(data=datf,aes(x=X1,y=value/FWD,fill=variable),stat="identity",position="stack")+geom_bar(data=datr,aes(x=X1,y=value*(-1)/RVS,fill=variable),stat="identity",position="stack") + scale_x_continuous(limits = c(320, 340)) + scale_y_continuous(limits = c(-0.1, 0.25))+labs(x="Reference position",y = "Diff-seq Coverage Frequencies")+theme_bw(base_size = 20)+ theme(panel.background = element_rect(fill ="transparent", colour = "black"),panel.grid.minor = element_blank(),panel.grid.major = element_blank())+theme(axis.text=element_text(size=20),axis.title=element_text(size=20),legend.text=element_text(size=16),legend.title=element_text(size=18))
ggplot() +geom_bar(data=datf,aes(x=X1,y=value/FWD,fill=variable),stat="identity",position="stack")+geom_bar(data=datr,aes(x=X1,y=value*(-1)/RVS,fill=variable),stat="identity",position="stack") + scale_x_continuous(limits = c(470, 490)) + scale_y_continuous(limits = c(-0.1, 0.25))+labs(x="Reference position",y = "Diff-seq Coverage Frequencies")+theme_bw(base_size = 20)+ theme(panel.background = element_rect(fill ="transparent", colour = "black"),panel.grid.minor = element_blank(),panel.grid.major = element_blank())+theme(axis.text=element_text(size=20),axis.title=element_text(size=20),legend.text=element_text(size=16),legend.title=element_text(size=18))
ggplot() +geom_bar(data=datf,aes(x=X1,y=value/FWD,fill=variable),stat="identity",position="stack")+geom_bar(data=datr,aes(x=X1,y=value*(-1)/RVS,fill=variable),stat="identity",position="stack") + scale_x_continuous(limits = c(460, 500)) + scale_y_continuous(limits = c(-0.1, 0.25))+labs(x="Reference position",y = "Diff-seq Coverage Frequencies")+theme_bw(base_size = 20)+ theme(panel.background = element_rect(fill ="transparent", colour = "black"),panel.grid.minor = element_blank(),panel.grid.major = element_blank())+theme(axis.text=element_text(size=20),axis.title=element_text(size=20),legend.text=element_text(size=16),legend.title=element_text(size=18))
dev.off()

